/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendingIndexRouteImport } from './routes/trending.index'
import { Route as TrendingAppleRouteImport } from './routes/trending.apple'
import { Route as PodcastPodIdRouteImport } from './routes/podcast.$podId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AuthedPodcastsIndexRouteImport } from './routes/_authed.podcasts.index'
import { Route as PodcastAppleItunesIdRouteImport } from './routes/podcast.apple_.$itunesId'
import { Route as AuthedPodcastsPodIdRouteImport } from './routes/_authed.podcasts.$podId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingIndexRoute = TrendingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrendingRoute,
} as any)
const TrendingAppleRoute = TrendingAppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => TrendingRoute,
} as any)
const PodcastPodIdRoute = PodcastPodIdRouteImport.update({
  id: '/podcast/$podId',
  path: '/podcast/$podId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPodcastsIndexRoute = AuthedPodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => AuthedRoute,
} as any)
const PodcastAppleItunesIdRoute = PodcastAppleItunesIdRouteImport.update({
  id: '/podcast/apple_/$itunesId',
  path: '/podcast/apple/$itunesId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPodcastsPodIdRoute = AuthedPodcastsPodIdRouteImport.update({
  id: '/podcasts/$podId',
  path: '/podcasts/$podId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/trending': typeof TrendingRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/podcast/$podId': typeof PodcastPodIdRoute
  '/trending/apple': typeof TrendingAppleRoute
  '/trending/': typeof TrendingIndexRoute
  '/podcasts/$podId': typeof AuthedPodcastsPodIdRoute
  '/podcast/apple/$itunesId': typeof PodcastAppleItunesIdRoute
  '/podcasts': typeof AuthedPodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/api/search': typeof ApiSearchRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/podcast/$podId': typeof PodcastPodIdRoute
  '/trending/apple': typeof TrendingAppleRoute
  '/trending': typeof TrendingIndexRoute
  '/podcasts/$podId': typeof AuthedPodcastsPodIdRoute
  '/podcast/apple/$itunesId': typeof PodcastAppleItunesIdRoute
  '/podcasts': typeof AuthedPodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/trending': typeof TrendingRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/podcast/$podId': typeof PodcastPodIdRoute
  '/trending/apple': typeof TrendingAppleRoute
  '/trending/': typeof TrendingIndexRoute
  '/_authed/podcasts/$podId': typeof AuthedPodcastsPodIdRoute
  '/podcast/apple_/$itunesId': typeof PodcastAppleItunesIdRoute
  '/_authed/podcasts/': typeof AuthedPodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/trending'
    | '/api/search'
    | '/auth/signin'
    | '/auth/signup'
    | '/podcast/$podId'
    | '/trending/apple'
    | '/trending/'
    | '/podcasts/$podId'
    | '/podcast/apple/$itunesId'
    | '/podcasts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/api/search'
    | '/auth/signin'
    | '/auth/signup'
    | '/podcast/$podId'
    | '/trending/apple'
    | '/trending'
    | '/podcasts/$podId'
    | '/podcast/apple/$itunesId'
    | '/podcasts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/discover'
    | '/trending'
    | '/api/search'
    | '/auth/signin'
    | '/auth/signup'
    | '/podcast/$podId'
    | '/trending/apple'
    | '/trending/'
    | '/_authed/podcasts/$podId'
    | '/podcast/apple_/$itunesId'
    | '/_authed/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  TrendingRoute: typeof TrendingRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PodcastPodIdRoute: typeof PodcastPodIdRoute
  PodcastAppleItunesIdRoute: typeof PodcastAppleItunesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending/': {
      id: '/trending/'
      path: '/'
      fullPath: '/trending/'
      preLoaderRoute: typeof TrendingIndexRouteImport
      parentRoute: typeof TrendingRoute
    }
    '/trending/apple': {
      id: '/trending/apple'
      path: '/apple'
      fullPath: '/trending/apple'
      preLoaderRoute: typeof TrendingAppleRouteImport
      parentRoute: typeof TrendingRoute
    }
    '/podcast/$podId': {
      id: '/podcast/$podId'
      path: '/podcast/$podId'
      fullPath: '/podcast/$podId'
      preLoaderRoute: typeof PodcastPodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/': {
      id: '/_authed/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof AuthedPodcastsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/podcast/apple_/$itunesId': {
      id: '/podcast/apple_/$itunesId'
      path: '/podcast/apple/$itunesId'
      fullPath: '/podcast/apple/$itunesId'
      preLoaderRoute: typeof PodcastAppleItunesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/podcasts/$podId': {
      id: '/_authed/podcasts/$podId'
      path: '/podcasts/$podId'
      fullPath: '/podcasts/$podId'
      preLoaderRoute: typeof AuthedPodcastsPodIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPodcastsPodIdRoute: typeof AuthedPodcastsPodIdRoute
  AuthedPodcastsIndexRoute: typeof AuthedPodcastsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPodcastsPodIdRoute: AuthedPodcastsPodIdRoute,
  AuthedPodcastsIndexRoute: AuthedPodcastsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface TrendingRouteChildren {
  TrendingAppleRoute: typeof TrendingAppleRoute
  TrendingIndexRoute: typeof TrendingIndexRoute
}

const TrendingRouteChildren: TrendingRouteChildren = {
  TrendingAppleRoute: TrendingAppleRoute,
  TrendingIndexRoute: TrendingIndexRoute,
}

const TrendingRouteWithChildren = TrendingRoute._addFileChildren(
  TrendingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  TrendingRoute: TrendingRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  PodcastPodIdRoute: PodcastPodIdRoute,
  PodcastAppleItunesIdRoute: PodcastAppleItunesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
